/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaseController } from "./BaseController";
export type { UserController } from "./UserController";
