/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface IRouteBridgeInterface extends utils.Interface {
  functions: {
    "setChildBridge(uint256,address)": FunctionFragment;
    "setNonEVMChildBridge(uint8,uint256)": FunctionFragment;
    "setRootBridge(uint256,address)": FunctionFragment;
    "setRootBridgeObserver(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "setChildBridge"
      | "setNonEVMChildBridge"
      | "setRootBridge"
      | "setRootBridgeObserver"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "setChildBridge",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setNonEVMChildBridge",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRootBridge",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRootBridgeObserver",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "setChildBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNonEVMChildBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRootBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRootBridgeObserver",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRouteBridge extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRouteBridgeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    setChildBridge(
      chainId: PromiseOrValue<BigNumberish>,
      childBridge: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setNonEVMChildBridge(
      nonEvmBridgeID: PromiseOrValue<BigNumberish>,
      txTemplateId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRootBridge(
      chainId: PromiseOrValue<BigNumberish>,
      rootBridge: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRootBridgeObserver(
      _observer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  setChildBridge(
    chainId: PromiseOrValue<BigNumberish>,
    childBridge: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setNonEVMChildBridge(
    nonEvmBridgeID: PromiseOrValue<BigNumberish>,
    txTemplateId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRootBridge(
    chainId: PromiseOrValue<BigNumberish>,
    rootBridge: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRootBridgeObserver(
    _observer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    setChildBridge(
      chainId: PromiseOrValue<BigNumberish>,
      childBridge: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setNonEVMChildBridge(
      nonEvmBridgeID: PromiseOrValue<BigNumberish>,
      txTemplateId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRootBridge(
      chainId: PromiseOrValue<BigNumberish>,
      rootBridge: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRootBridgeObserver(
      _observer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    setChildBridge(
      chainId: PromiseOrValue<BigNumberish>,
      childBridge: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setNonEVMChildBridge(
      nonEvmBridgeID: PromiseOrValue<BigNumberish>,
      txTemplateId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRootBridge(
      chainId: PromiseOrValue<BigNumberish>,
      rootBridge: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRootBridgeObserver(
      _observer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    setChildBridge(
      chainId: PromiseOrValue<BigNumberish>,
      childBridge: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setNonEVMChildBridge(
      nonEvmBridgeID: PromiseOrValue<BigNumberish>,
      txTemplateId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRootBridge(
      chainId: PromiseOrValue<BigNumberish>,
      rootBridge: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRootBridgeObserver(
      _observer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
