/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export declare namespace MetaDataResolver {
  export type KeyValMetaStruct = {
    key: PromiseOrValue<BytesLike>;
    dType: PromiseOrValue<BigNumberish>;
    dValue: PromiseOrValue<BytesLike>;
    editable: PromiseOrValue<boolean>;
    encrypted: PromiseOrValue<boolean>;
  };

  export type KeyValMetaStructOutput = [
    string,
    number,
    string,
    boolean,
    boolean
  ] & {
    key: string;
    dType: number;
    dValue: string;
    editable: boolean;
    encrypted: boolean;
  };
}

export interface UserDataServiceResolverInterface extends utils.Interface {
  functions: {
    "authorisations(bytes32,address,address)": FunctionFragment;
    "ident(uint256)": FunctionFragment;
    "metaValue(uint256,string)": FunctionFragment;
    "metadata(uint256)": FunctionFragment;
    "multicall(bytes[])": FunctionFragment;
    "name(uint256)": FunctionFragment;
    "profile(uint256)": FunctionFragment;
    "setAuthorisation(bytes32,address,bool)": FunctionFragment;
    "setMetaData(uint256,string,uint256,bytes,bool,bool)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "authorisations"
      | "ident"
      | "metaValue"
      | "metadata"
      | "multicall"
      | "name"
      | "profile"
      | "setAuthorisation"
      | "setMetaData"
      | "supportsInterface"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "authorisations",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "ident",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "metaValue",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "metadata",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "multicall",
    values: [PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "name",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "profile",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorisation",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setMetaData",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorisations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ident", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "metaValue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "metadata", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "profile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorisation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMetaData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;

  events: {
    "AuthorisationChanged(bytes32,address,address,bool)": EventFragment;
    "MetaDataAdded(uint256,bytes32,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuthorisationChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MetaDataAdded"): EventFragment;
}

export interface AuthorisationChangedEventObject {
  profileId: string;
  owner: string;
  target: string;
  isAuthorised: boolean;
}
export type AuthorisationChangedEvent = TypedEvent<
  [string, string, string, boolean],
  AuthorisationChangedEventObject
>;

export type AuthorisationChangedEventFilter =
  TypedEventFilter<AuthorisationChangedEvent>;

export interface MetaDataAddedEventObject {
  tokenid: BigNumber;
  metaid: string;
  keyid: string;
}
export type MetaDataAddedEvent = TypedEvent<
  [BigNumber, string, string],
  MetaDataAddedEventObject
>;

export type MetaDataAddedEventFilter = TypedEventFilter<MetaDataAddedEvent>;

export interface UserDataServiceResolver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UserDataServiceResolverInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    authorisations(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    ident(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    metaValue(
      tokenId: PromiseOrValue<BigNumberish>,
      keyStr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [MetaDataResolver.KeyValMetaStructOutput] & {
        kv: MetaDataResolver.KeyValMetaStructOutput;
      }
    >;

    metadata(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    multicall(
      data: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    name(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    profile(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setAuthorisation(
      profileId: PromiseOrValue<BytesLike>,
      target: PromiseOrValue<string>,
      isAuthorised: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMetaData(
      tokenId: PromiseOrValue<BigNumberish>,
      keyStr: PromiseOrValue<string>,
      _dtype: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BytesLike>,
      editable: PromiseOrValue<boolean>,
      encrypted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  authorisations(
    arg0: PromiseOrValue<BytesLike>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  ident(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  metaValue(
    tokenId: PromiseOrValue<BigNumberish>,
    keyStr: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<MetaDataResolver.KeyValMetaStructOutput>;

  metadata(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  multicall(
    data: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  name(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  profile(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  setAuthorisation(
    profileId: PromiseOrValue<BytesLike>,
    target: PromiseOrValue<string>,
    isAuthorised: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMetaData(
    tokenId: PromiseOrValue<BigNumberish>,
    keyStr: PromiseOrValue<string>,
    _dtype: PromiseOrValue<BigNumberish>,
    value: PromiseOrValue<BytesLike>,
    editable: PromiseOrValue<boolean>,
    encrypted: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceID: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    authorisations(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    ident(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    metaValue(
      tokenId: PromiseOrValue<BigNumberish>,
      keyStr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<MetaDataResolver.KeyValMetaStructOutput>;

    metadata(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    multicall(
      data: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<string[]>;

    name(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    profile(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    setAuthorisation(
      profileId: PromiseOrValue<BytesLike>,
      target: PromiseOrValue<string>,
      isAuthorised: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMetaData(
      tokenId: PromiseOrValue<BigNumberish>,
      keyStr: PromiseOrValue<string>,
      _dtype: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BytesLike>,
      editable: PromiseOrValue<boolean>,
      encrypted: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "AuthorisationChanged(bytes32,address,address,bool)"(
      profileId?: PromiseOrValue<BytesLike> | null,
      owner?: PromiseOrValue<string> | null,
      target?: PromiseOrValue<string> | null,
      isAuthorised?: null
    ): AuthorisationChangedEventFilter;
    AuthorisationChanged(
      profileId?: PromiseOrValue<BytesLike> | null,
      owner?: PromiseOrValue<string> | null,
      target?: PromiseOrValue<string> | null,
      isAuthorised?: null
    ): AuthorisationChangedEventFilter;

    "MetaDataAdded(uint256,bytes32,bytes32)"(
      tokenid?: null,
      metaid?: null,
      keyid?: null
    ): MetaDataAddedEventFilter;
    MetaDataAdded(
      tokenid?: null,
      metaid?: null,
      keyid?: null
    ): MetaDataAddedEventFilter;
  };

  estimateGas: {
    authorisations(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ident(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    metaValue(
      tokenId: PromiseOrValue<BigNumberish>,
      keyStr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    metadata(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    multicall(
      data: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    name(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    profile(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setAuthorisation(
      profileId: PromiseOrValue<BytesLike>,
      target: PromiseOrValue<string>,
      isAuthorised: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMetaData(
      tokenId: PromiseOrValue<BigNumberish>,
      keyStr: PromiseOrValue<string>,
      _dtype: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BytesLike>,
      editable: PromiseOrValue<boolean>,
      encrypted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    authorisations(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ident(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    metaValue(
      tokenId: PromiseOrValue<BigNumberish>,
      keyStr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    metadata(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    multicall(
      data: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    name(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    profile(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAuthorisation(
      profileId: PromiseOrValue<BytesLike>,
      target: PromiseOrValue<string>,
      isAuthorised: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMetaData(
      tokenId: PromiseOrValue<BigNumberish>,
      keyStr: PromiseOrValue<string>,
      _dtype: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BytesLike>,
      editable: PromiseOrValue<boolean>,
      encrypted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
