/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC2055 } from "./ERC2055";
export type { ERC2055Storage } from "./ERC2055Storage";
export type { IERC2055 } from "./IERC2055";
