/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface XWrapperInterface extends utils.Interface {
  functions: {
    "initialize(address,address,uint256,bytes32,bool)": FunctionFragment;
    "wrap()": FunctionFragment;
    "wrapERC1155(address)": FunctionFragment;
    "wrapERC20(address)": FunctionFragment;
    "wrapERC721(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "initialize"
      | "wrap"
      | "wrapERC1155"
      | "wrapERC20"
      | "wrapERC721"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(functionFragment: "wrap", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "wrapERC1155",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "wrapERC20",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "wrapERC721",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wrap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "wrapERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wrapERC20", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wrapERC721", data: BytesLike): Result;

  events: {
    "Initialized(uint8)": EventFragment;
    "NewTokenWrapped(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewTokenWrapped"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface NewTokenWrappedEventObject {
  _token: string;
}
export type NewTokenWrappedEvent = TypedEvent<
  [string],
  NewTokenWrappedEventObject
>;

export type NewTokenWrappedEventFilter = TypedEventFilter<NewTokenWrappedEvent>;

export interface XWrapper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: XWrapperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    initialize(
      _owner: PromiseOrValue<string>,
      _implementation: PromiseOrValue<string>,
      ercType: PromiseOrValue<BigNumberish>,
      salt: PromiseOrValue<BytesLike>,
      isPresale: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    wrap(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    wrapERC1155(
      _implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    wrapERC20(
      _implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    wrapERC721(
      _implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  initialize(
    _owner: PromiseOrValue<string>,
    _implementation: PromiseOrValue<string>,
    ercType: PromiseOrValue<BigNumberish>,
    salt: PromiseOrValue<BytesLike>,
    isPresale: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  wrap(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  wrapERC1155(
    _implementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  wrapERC20(
    _implementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  wrapERC721(
    _implementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    initialize(
      _owner: PromiseOrValue<string>,
      _implementation: PromiseOrValue<string>,
      ercType: PromiseOrValue<BigNumberish>,
      salt: PromiseOrValue<BytesLike>,
      isPresale: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    wrap(overrides?: CallOverrides): Promise<string>;

    wrapERC1155(
      _implementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    wrapERC20(
      _implementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    wrapERC721(
      _implementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "NewTokenWrapped(address)"(_token?: null): NewTokenWrappedEventFilter;
    NewTokenWrapped(_token?: null): NewTokenWrappedEventFilter;
  };

  estimateGas: {
    initialize(
      _owner: PromiseOrValue<string>,
      _implementation: PromiseOrValue<string>,
      ercType: PromiseOrValue<BigNumberish>,
      salt: PromiseOrValue<BytesLike>,
      isPresale: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    wrap(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    wrapERC1155(
      _implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    wrapERC20(
      _implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    wrapERC721(
      _implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    initialize(
      _owner: PromiseOrValue<string>,
      _implementation: PromiseOrValue<string>,
      ercType: PromiseOrValue<BigNumberish>,
      salt: PromiseOrValue<BytesLike>,
      isPresale: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    wrap(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    wrapERC1155(
      _implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    wrapERC20(
      _implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    wrapERC721(
      _implementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
