/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IAKXInterface extends utils.Interface {
  functions: {
    "DexToken(address)": FunctionFragment;
    "EthDIDRegistry()": FunctionFragment;
    "LabzToken()": FunctionFragment;
    "UserDataService()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DexToken"
      | "EthDIDRegistry"
      | "LabzToken"
      | "UserDataService"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DexToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "EthDIDRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "LabzToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "UserDataService",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "DexToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "EthDIDRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "LabzToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "UserDataService",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IAKX extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IAKXInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DexToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    EthDIDRegistry(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    LabzToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    UserDataService(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  DexToken(
    token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  EthDIDRegistry(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  LabzToken(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  UserDataService(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DexToken(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    EthDIDRegistry(overrides?: CallOverrides): Promise<string>;

    LabzToken(overrides?: CallOverrides): Promise<string>;

    UserDataService(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    DexToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    EthDIDRegistry(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    LabzToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    UserDataService(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DexToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    EthDIDRegistry(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    LabzToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    UserDataService(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
