/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace MetaDataResolver {
  export type KeyValMetaStruct = {
    key: PromiseOrValue<BytesLike>;
    dType: PromiseOrValue<BigNumberish>;
    dValue: PromiseOrValue<BytesLike>;
    editable: PromiseOrValue<boolean>;
    encrypted: PromiseOrValue<boolean>;
  };

  export type KeyValMetaStructOutput = [
    string,
    number,
    string,
    boolean,
    boolean
  ] & {
    key: string;
    dType: number;
    dValue: string;
    editable: boolean;
    encrypted: boolean;
  };
}

export interface AllResolversInterface extends utils.Interface {
  functions: {
    "ident(uint256)": FunctionFragment;
    "metaValue(uint256,string)": FunctionFragment;
    "metadata(uint256)": FunctionFragment;
    "name(uint256)": FunctionFragment;
    "profile(uint256)": FunctionFragment;
    "setMetaData(uint256,string,uint256,bytes,bool,bool)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "ident"
      | "metaValue"
      | "metadata"
      | "name"
      | "profile"
      | "setMetaData"
      | "supportsInterface"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ident",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "metaValue",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "metadata",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "name",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "profile",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMetaData",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "ident", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "metaValue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "metadata", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "profile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMetaData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;

  events: {
    "MetaDataAdded(uint256,bytes32,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MetaDataAdded"): EventFragment;
}

export interface MetaDataAddedEventObject {
  tokenid: BigNumber;
  metaid: string;
  keyid: string;
}
export type MetaDataAddedEvent = TypedEvent<
  [BigNumber, string, string],
  MetaDataAddedEventObject
>;

export type MetaDataAddedEventFilter = TypedEventFilter<MetaDataAddedEvent>;

export interface AllResolvers extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AllResolversInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ident(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    metaValue(
      tokenId: PromiseOrValue<BigNumberish>,
      keyStr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [MetaDataResolver.KeyValMetaStructOutput] & {
        kv: MetaDataResolver.KeyValMetaStructOutput;
      }
    >;

    metadata(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    name(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    profile(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setMetaData(
      tokenId: PromiseOrValue<BigNumberish>,
      keyStr: PromiseOrValue<string>,
      _dtype: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BytesLike>,
      editable: PromiseOrValue<boolean>,
      encrypted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  ident(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  metaValue(
    tokenId: PromiseOrValue<BigNumberish>,
    keyStr: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<MetaDataResolver.KeyValMetaStructOutput>;

  metadata(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  name(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  profile(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  setMetaData(
    tokenId: PromiseOrValue<BigNumberish>,
    keyStr: PromiseOrValue<string>,
    _dtype: PromiseOrValue<BigNumberish>,
    value: PromiseOrValue<BytesLike>,
    editable: PromiseOrValue<boolean>,
    encrypted: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceID: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    ident(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    metaValue(
      tokenId: PromiseOrValue<BigNumberish>,
      keyStr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<MetaDataResolver.KeyValMetaStructOutput>;

    metadata(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    name(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    profile(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    setMetaData(
      tokenId: PromiseOrValue<BigNumberish>,
      keyStr: PromiseOrValue<string>,
      _dtype: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BytesLike>,
      editable: PromiseOrValue<boolean>,
      encrypted: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "MetaDataAdded(uint256,bytes32,bytes32)"(
      tokenid?: null,
      metaid?: null,
      keyid?: null
    ): MetaDataAddedEventFilter;
    MetaDataAdded(
      tokenid?: null,
      metaid?: null,
      keyid?: null
    ): MetaDataAddedEventFilter;
  };

  estimateGas: {
    ident(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    metaValue(
      tokenId: PromiseOrValue<BigNumberish>,
      keyStr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    metadata(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    profile(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setMetaData(
      tokenId: PromiseOrValue<BigNumberish>,
      keyStr: PromiseOrValue<string>,
      _dtype: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BytesLike>,
      editable: PromiseOrValue<boolean>,
      encrypted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ident(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    metaValue(
      tokenId: PromiseOrValue<BigNumberish>,
      keyStr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    metadata(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    profile(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setMetaData(
      tokenId: PromiseOrValue<BigNumberish>,
      keyStr: PromiseOrValue<string>,
      _dtype: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BytesLike>,
      editable: PromiseOrValue<boolean>,
      encrypted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
