/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uds from "./uds";
export type { uds };
export type { BaseModule } from "./BaseModule";
export type { DidRegistry } from "./DidRegistry";
export type { ModuleRegistry } from "./ModuleRegistry";
export type { ModuleStorage } from "./ModuleStorage";
export type { ModulesManager } from "./ModulesManager";
