/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Account } from "./Account";
export type { Bank } from "./Bank";
export type { IBank } from "./IBank";
