/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as accountSol from "./Account.sol";
export { Bank__factory } from "./Bank__factory";
export { IBank__factory } from "./IBank__factory";
